feat(Achievements): many to many table
Kryha/bot-busters pull request #171
Opened 2024-01-12 08:55 UTC by Mautjee

## Description

This pull request adds a new many-to-many table and implements the functionality to set and get user matches. It also includes various file changes related to the implementation.

2024-01-12 11:52 UTC, ramidecodes approved these changes

2024-01-12 14:16 UTC, silimarius requested changes

2024-01-12 14:16 UTC, silimarius commented on src/server/db/user.ts
> +    .from(usersToMatches)
If I recall correctly, the correct way to do such a join would be to select from users table, then inner join with the usersToMatches then a second inner join with matches

2024-01-12 14:16 UTC, silimarius commented on src/server/service/match.ts
I don't think you even need the `getPlayerPreviousMatches` method anymore since it's enough to just perform the select with joins. Also this function does not belong here since we are only supposed to declare methods that relate to the match instance here

2024-01-16 10:43 UTC, silimarius approved these changes

2024-01-16 10:43 UTC, silimarius commented on src/server/db/match.ts
> +  });
```suggestion
  await Promise.all(promises);
```
this way if an error is thrown, useMutation will return the error properly

2024-01-16 10:43 UTC, silimarius commented on src/server/service/match.ts
> +      // TODO: handle
console.error for now

2024-01-16 15:10 UTC, merged