bug(authentication) fix double clicking to proceed
Kryha/bot-busters pull request #195
Opened 2024-01-17 14:40 UTC by Mautjee

## Description 

User now presses once to proceed to the next stage

## Changes

closes#194

2024-01-17 15:17 UTC, silimarius requested changes

2024-01-17 15:17 UTC, silimarius commented on src/containers/results/results.tsx
> +          setMergeRequested(false);
this should be above router.push, else this gets triggered after components unmounts and that's a leak

2024-01-17 15:28 UTC, silimarius commented on src/containers/results/results.tsx
> +          setMergeRequested(false);
This would not solve my comment since it would still be executed after

2024-01-17 15:38 UTC, ramidecodes approved these changes

2024-01-18 08:42 UTC, silimarius commented on src/containers/results/results.tsx
> +          setMergeRequested(false);
Then we're back to the beginning and the double clicking would be back

2024-01-18 12:06 UTC, silimarius approved these changes

2024-01-18 12:13 UTC, merged